"""
Alert Model - System notifications and warnings.
This model stores all alerts generated by the system (low stock, expiry, etc.)
"""

from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey
from sqlalchemy.sql import func
from core.database import Base


class Alert(Base):
    """
    Alert/Notification model.
    Stores system-generated alerts for pharmacy staff.
    """
    __tablename__ = "alerts"

    # Primary key
    id = Column(Integer, primary_key=True, index=True)
    
    # Alert type
    alert_type = Column(String(50), nullable=False, index=True)
    # Types: 'low_stock', 'expiry', 'anomaly', 'forecast', 'system'
    
    # Priority level
    priority = Column(String(20), default="medium")
    # Levels: 'critical', 'high', 'medium', 'low'
    
    # Alert content
    title = Column(String(255), nullable=False)
    message = Column(Text, nullable=False)
    
    # Related entities (optional)
    medicine_id = Column(Integer, ForeignKey("medicines.id"), nullable=True)
    inventory_id = Column(Integer, ForeignKey("inventory.id"), nullable=True)
    
    # Status
    status = Column(String(20), default="unread")
    # Status: 'unread', 'acknowledged', 'resolved'
    
    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    acknowledged_at = Column(DateTime(timezone=True), nullable=True)
    resolved_at = Column(DateTime(timezone=True), nullable=True)

    def to_dict(self):
        """Convert model to dictionary for API responses"""
        return {
            "id": self.id,
            "alert_type": self.alert_type,
            "priority": self.priority,
            "title": self.title,
            "message": self.message,
            "medicine_id": self.medicine_id,
            "inventory_id": self.inventory_id,
            "status": self.status,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "acknowledged_at": self.acknowledged_at.isoformat() if self.acknowledged_at else None,
            "resolved_at": self.resolved_at.isoformat() if self.resolved_at else None,
        }
